# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
