# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160304_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='linkedin_username',
            field=models.CharField(default='what', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=40221672, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employees'),
        ),
    ]
